# Site settings
title: Tongan Vet Clinic
email: tonganvet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is for the Tongan Vet Clinic.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tonganvet.github.io/" # the base hostname & protocol for your site

# User setting
owner: Tongan Vet | Kingdom of Tonga, Ministry of Agriculture & Food, Forest & Fisheries
email: tonganvet@gmail.com
facebook_username: example
address:
  - line: "Tokomololo, Nuku ªalofa, Tongatapu Island, Kingdom of Tonga"
  # Feel free to add more lines here 
telephone:  +676 29715
copyright: MAFF Tongan Vet Clinic 

# API settings
google_api_key: AIzaSyCZt_VdD0tTSHlX3faDyVn5Vo90ss7Ubg8


# Build settings
markdown: kramdown
